### PR TITLE
added web socket communication and logic to join a lobby

### PR DESCRIPTION
**Pull request by SandroLinder**
Issue: https://github.com/SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid/issues/28

Work done:
- web socket communication works in both directions
- you can join a lobby on the server
- you get a toast when another player joins your lobby

### CODE REVIEW

**Review by TheNerm — APPROVED** [review]
On the simulator, the build works perfectly fine (as long as the server project is being executed at the same time).

**Comment by SandroLinder** [comment]
I cannot really test the remaining methods because they are only called when a connection is opened/closed or an exception happens. Will merge it even though it has less than 80 coverage.

**Comment by SonjaRass** [comment]
Merge under 80% coverage okay.. see command Sandro from 20.4.22

**Review by SonjaRass — APPROVED** [review]
redo review after pull request was closed accidentally
sorry sorry

**Comment by d2rainer** [comment]
Merge under 80% is fine based on above mentioned arguments.

**Review by claudialei — COMMENTED** [review]
looks fine to me. Maybe it's possible to rise the coverage later on

**Pull request merged**
